import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Brain, Sparkles, Users, BarChart3, Shield, Trophy,
  ChevronDown, ChevronUp, Copy, Check, Printer, Trash2,
  Loader2, AlertCircle, Globe, Filter, Calendar
} from "lucide-react";
import { useApi } from "../hooks/useApi";
import { GRADE_LEVELS, LANGUAGES } from "../utils/constants";

const FOCUS_AREAS = [
  {
    value: "overall",
    label: "Overall Analysis",
    description: "Comprehensive review of all classroom aspects",
    icon: BarChart3,
    color: "bg-blue-50 text-blue-600 border-blue-200",
  },
  {
    value: "academic",
    label: "Academic Focus",
    description: "Deep dive into grades, ratings & learning outcomes",
    icon: Trophy,
    color: "bg-amber-50 text-amber-600 border-amber-200",
  },
  {
    value: "behavioral",
    label: "Behavioral & Social",
    description: "Discipline, participation & social dynamics",
    icon: Users,
    color: "bg-emerald-50 text-emerald-600 border-emerald-200",
  },
  {
    value: "at_risk",
    label: "At-Risk Students",
    description: "Students needing immediate attention",
    icon: Shield,
    color: "bg-red-50 text-red-600 border-red-200",
  },
  {
    value: "strengths",
    label: "Strengths & Celebrations",
    description: "What the class is doing well",
    icon: Sparkles,
    color: "bg-violet-50 text-violet-600 border-violet-200",
  },
];

function formatDate(iso) {
  return new Date(iso).toLocaleDateString("en-IN", {
    day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });
}

export default function ClassroomInsightsPage({ user }) {
  const [focusArea, setFocusArea] = useState("overall");
  const [gradeFilter, setGradeFilter] = useState("");
  const [language, setLanguage] = useState("english");
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  const { execute } = useApi();

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const data = await execute(`/insights/history?user_id=${user.id}`);
      setHistory(data);
    } catch {}
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    setResult(null);
    try {
      const body = {
        user_id: user.id,
        focus_area: focusArea,
        language,
      };
      if (gradeFilter) body.grade_filter = gradeFilter;
      const data = await execute("/insights/generate", {
        method: "POST",
        body: JSON.stringify(body),
      });
      setResult(data);
      fetchHistory();
    } catch (err) {
      setError(err?.message || "Failed to generate insights. Make sure you have feedback data.");
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.insights_text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    if (!result) return;
    const focusLabel = FOCUS_AREAS.find((f) => f.value === result.focus_area)?.label || result.focus_area;
    const printWindow = window.open("", "_blank");
    printWindow.document.write(`<!DOCTYPE html><html><head><title>Classroom Insights</title>
      <style>
        body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.7; }
        h1 { font-size: 22px; border-bottom: 2px solid #2563eb; padding-bottom: 8px; color: #1e3a5f; }
        .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
        .content { font-size: 15px; white-space: pre-wrap; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
      </style></head><body>
      <h1>Classroom Insights — ${focusLabel}</h1>
      <div class="meta">
        ${result.student_count} students · ${result.feedback_count} feedback entries
        ${result.grade_filter ? ` · Grade: ${result.grade_filter}` : ""}
        · Generated: ${formatDate(result.created_at)}
      </div>
      <div class="content">${result.insights_text}</div>
      <div class="footer">Generated by Teacher Toolkit</div>
      </body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  const handleDeleteHistory = async (id) => {
    try {
      await execute(`/insights/history/${id}`, { method: "DELETE" });
      setHistory((prev) => prev.filter((h) => h.id !== id));
      if (result?.id === id) setResult(null);
    } catch {}
  };

  const handleLoadFromHistory = (item) => {
    setResult(item);
    setShowHistory(false);
  };

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
            <Brain className="w-5 h-5 text-indigo-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-text-primary">Classroom Insights</h1>
            <p className="text-sm text-text-secondary">
              AI-powered analysis of your entire classroom's feedback data
            </p>
          </div>
        </div>
      </div>

      {/* Focus Area Selection */}
      <div className="glass-panel p-5 mb-4">
        <h2 className="text-sm font-semibold text-text-primary mb-3">Choose Analysis Focus</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2">
          {FOCUS_AREAS.map((area) => {
            const Icon = area.icon;
            const selected = focusArea === area.value;
            return (
              <button
                key={area.value}
                onClick={() => setFocusArea(area.value)}
                className={`flex flex-col items-start p-3 rounded-xl border-2 transition-all text-left ${
                  selected
                    ? "border-primary bg-primary/5 ring-1 ring-primary/20"
                    : "border-border-light hover:border-primary/30 hover:bg-panel/50"
                }`}
              >
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center mb-2 ${area.color}`}>
                  <Icon className="w-4 h-4" />
                </div>
                <span className="text-xs font-semibold text-text-primary">{area.label}</span>
                <span className="text-[10px] text-muted mt-0.5 leading-tight">{area.description}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Filters & Generate */}
      <div className="glass-panel p-5 mb-4">
        <div className="flex flex-col sm:flex-row gap-3 items-end">
          <div className="flex-1">
            <label className="block text-xs font-medium text-text-secondary mb-1.5">
              <Filter className="w-3 h-3 inline mr-1" />
              Filter by Grade (optional)
            </label>
            <select
              value={gradeFilter}
              onChange={(e) => setGradeFilter(e.target.value)}
              className="input-field text-sm"
            >
              <option value="">All Grades</option>
              {GRADE_LEVELS.map((g) => (
                <option key={g} value={g}>{g}</option>
              ))}
            </select>
          </div>
          <div className="flex-1">
            <label className="block text-xs font-medium text-text-secondary mb-1.5">
              <Globe className="w-3 h-3 inline mr-1" />
              Language
            </label>
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              className="input-field text-sm"
            >
              {LANGUAGES.map((l) => (
                <option key={l.value} value={l.value}>{l.label}</option>
              ))}
            </select>
          </div>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="btn-primary flex items-center gap-2 px-6 py-2.5 whitespace-nowrap"
          >
            {generating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Analyzing Classroom...
              </>
            ) : (
              <>
                <Brain className="w-4 h-4" />
                Generate Insights
              </>
            )}
          </button>
        </div>
      </div>

      {/* Error */}
      {error && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-2 p-3 mb-4 bg-red-50 text-red-700 rounded-xl text-sm border border-red-200"
        >
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          {error}
        </motion.div>
      )}

      {/* Loading State */}
      {generating && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="glass-panel p-12 text-center mb-4"
        >
          <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex items-center justify-center mx-auto mb-4">
            <Brain className="w-8 h-8 text-indigo-600 animate-pulse" />
          </div>
          <h3 className="font-medium text-text-primary mb-1">Analyzing your classroom data...</h3>
          <p className="text-sm text-text-secondary">
            Reviewing all student feedback, identifying patterns, and generating insights.
          </p>
        </motion.div>
      )}

      {/* Result */}
      {result && !generating && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-panel overflow-hidden mb-4"
        >
          <div className="p-5 border-b border-border-light">
            <div className="flex items-center justify-between flex-wrap gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
                  <Brain className="w-5 h-5 text-indigo-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-text-primary">
                    {FOCUS_AREAS.find((f) => f.value === result.focus_area)?.label || "Classroom Insights"}
                  </h3>
                  <p className="text-xs text-muted">
                    {result.student_count} students · {result.feedback_count} feedback entries
                    {result.grade_filter ? ` · ${result.grade_filter}` : ""}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-text-secondary hover:text-primary hover:bg-panel rounded-lg transition-colors"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-success" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-text-secondary hover:text-primary hover:bg-panel rounded-lg transition-colors"
                >
                  <Printer className="w-3.5 h-3.5" />
                  Print
                </button>
              </div>
            </div>
          </div>
          <div className="p-5">
            <div className="bg-panel p-5 rounded-xl text-sm text-text-primary whitespace-pre-wrap leading-relaxed">
              {result.insights_text}
            </div>
          </div>
        </motion.div>
      )}

      {/* Empty state when no result and not generating */}
      {!result && !generating && !error && (
        <div className="glass-panel p-12 text-center mb-4">
          <div className="w-16 h-16 rounded-2xl bg-panel flex items-center justify-center mx-auto mb-4">
            <Brain className="w-8 h-8 text-muted/40" />
          </div>
          <h3 className="font-medium text-text-primary mb-1">Generate classroom insights</h3>
          <p className="text-sm text-text-secondary">
            Choose a focus area and click "Generate Insights" to get an AI-powered analysis of your classroom.
          </p>
        </div>
      )}

      {/* History */}
      {history.length > 0 && (
        <div className="glass-panel overflow-hidden">
          <button
            onClick={() => setShowHistory(!showHistory)}
            className="w-full flex items-center justify-between p-4 hover:bg-panel/50 transition-colors"
          >
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-muted" />
              <span className="text-sm font-medium text-text-primary">
                Past Insights ({history.length})
              </span>
            </div>
            {showHistory ? (
              <ChevronUp className="w-4 h-4 text-muted" />
            ) : (
              <ChevronDown className="w-4 h-4 text-muted" />
            )}
          </button>

          <AnimatePresence>
            {showHistory && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: "auto", opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                <div className="border-t border-border-light divide-y divide-border-light/50">
                  {history.map((item) => (
                    <div
                      key={item.id}
                      className="flex items-center justify-between p-4 hover:bg-panel/30 transition-colors"
                    >
                      <button
                        onClick={() => handleLoadFromHistory(item)}
                        className="flex-1 text-left min-w-0"
                      >
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-sm font-medium text-text-primary">
                            {FOCUS_AREAS.find((f) => f.value === item.focus_area)?.label || item.focus_area}
                          </span>
                          <span className="badge-blue text-xs">
                            {item.student_count} students
                          </span>
                          {item.grade_filter && (
                            <span className="badge-green text-xs">{item.grade_filter}</span>
                          )}
                          {item.language && item.language !== "english" && (
                            <span className="badge text-xs bg-indigo-50 text-indigo-700">
                              {LANGUAGES.find((l) => l.value === item.language)?.label?.split(" (")[0] || item.language}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-muted">{formatDate(item.created_at)}</p>
                      </button>
                      <button
                        onClick={() => handleDeleteHistory(item.id)}
                        className="p-2 text-muted hover:text-danger hover:bg-red-50 rounded-lg transition-colors flex-shrink-0"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
}
